manifest-version = 1

[component]
name = "example-rust-component"
version = "1.0.0"

# TODO: update the following fields once its available on API
category = "data-collection"
subcategory = "warehouse"
description = "Example Rust component for consent-mapping"
documentation = "https://github.com/edgee-cloud/example-rust-component"
repository = "https://github.com/edgee-cloud/example-rust-component"
language = "Rust"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && mv ./target/wasm32-wasip2/release/example_rust_component.wasm ./cmp_component.wasm"
output_path = "cmp_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
