manifest-version = 1

[component]
name = "example-rust-edge-function-component"
version = "1.0.0"

category = "edge-function"
subcategory = "wasm-function"
description = '''
## Overview

Describe **what this component does** and why it exists.

---

## ✨ Key Features & Benefits

### Features

- **Feature 1**: Quick feature description.
- **Feature 2**: Quick feature description.

### Benefits

- **Benefit 1**: Quick benefit description.
- **Benefit 1**: Quick benefit description.

---

## 🚀️ Use Cases

- **Use Case 1**: Quick use case description.
- **Use Case 2**: Quick use case description.

---

Additional resources: [Resource example](https://your-resource-link.com)
'''
documentation = "https://github.com/edgee-cloud/example-rust-component"
repository = "https://github.com/edgee-cloud/example-rust-component"
language = "Rust"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && rm -f ./component.wasm && mv ./target/wasm32-wasip2/release/example_rust_edge_function_component.wasm ./component.wasm"
output_path = "component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
